// Generates the rotated paper-plane cursors: `node scripts/gen-cursors.mjs`
//
// The cursor stays a native OS cursor (zero lag); <PlaneDirection/> only sets html[data-plane] to the
// heading bucket and the generated CSS picks the matching image. Per heading (24, every 15°) × variant
// (plane, hover) we render PNG @1x (32×32) and @2x (64×64): PNG is the format every browser supports for
// cursors (Safari is unreliable with SVG), and the @2x image keeps it sharp on Retina/HiDPI screens.
// Hotspot = the plane's nose, snapped to a whole pixel.
import fs from "node:fs";
import { Resvg } from "@resvg/resvg-js";

const SIZE = 32;
const STEP = 15;
const NOSE = [1, 1];
const HEADING = -133.2; // direction the source drawing points (nose (1,1) along the fold from (16,17))
const SHAPES = {
  plane: [
    { pts: [[16, 17], [8, 28], [13, 22]], fill: "#94A3B8" },
    { pts: [[1, 1], [16, 17], [28, 8]], fill: "#E2E8F0" },
    { pts: [[1, 1], [8, 28], [16, 17]], fill: "#FFFFFF" },
  ],
  hover: [
    { pts: [[16, 17], [8, 28], [13, 22]], fill: "#1F6BFF" },
    { pts: [[1, 1], [16, 17], [28, 8]], fill: "#BFD6FF" },
    { pts: [[1, 1], [8, 28], [16, 17]], fill: "#FFFFFF" },
  ],
};

const rot = ([x, y], deg) => {
  const r = (deg * Math.PI) / 180;
  const dx = x - NOSE[0];
  const dy = y - NOSE[1];
  return [NOSE[0] + dx * Math.cos(r) - dy * Math.sin(r), NOSE[1] + dx * Math.sin(r) + dy * Math.cos(r)];
};

const OUT = "public/cursors";
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
const INTERACTIVE = `a, button, [role="button"], label, select, summary, .cursor-pointer, input[type="checkbox"], input[type="radio"], input[type="submit"], input[type="button"], input[type="file"]`;
const REST = Math.round((HEADING + 180) / STEP); // bucket closest to how the source drawing points

const png = (svg, size) => new Resvg(svg, { fitTo: { mode: "width", value: size } }).render().asPng();
const rules = [];
for (let i = 0; i < 360 / STEP; i++) {
  const heading = -180 + i * STEP; // -180 … 165
  const r = heading - HEADING;
  const all = SHAPES.plane.flatMap((s) => s.pts.map((p) => rot(p, r)));
  const xs = all.map((p) => p[0]);
  const ys = all.map((p) => p[1]);
  const pad = 1.2; // half the stroke plus a hair
  const w = Math.max(...xs) - Math.min(...xs) + pad * 2;
  const h = Math.max(...ys) - Math.min(...ys) + pad * 2;
  const s = Math.min(1, (SIZE - 1) / Math.max(w, h));
  // centre the rotated plane, then nudge so the nose lands exactly on a pixel (the hotspot)
  let tx = SIZE / 2 - ((Math.min(...xs) + Math.max(...xs)) / 2) * s;
  let ty = SIZE / 2 - ((Math.min(...ys) + Math.max(...ys)) / 2) * s;
  const nx = NOSE[0] * s + tx;
  const ny = NOSE[1] * s + ty;
  tx += Math.round(nx) - nx;
  ty += Math.round(ny) - ny;
  const hx = Math.min(SIZE - 1, Math.max(0, Math.round(NOSE[0] * s + tx)));
  const hy = Math.min(SIZE - 1, Math.max(0, Math.round(NOSE[1] * s + ty)));
  const cursorValue = {};
  for (const [variant, polys] of Object.entries(SHAPES)) {
    const body = polys
      .map((p) => `<polygon points="${p.pts.map((pt) => rot(pt, r).map((v) => v.toFixed(2)).join(",")).join(" ")}" fill="${p.fill}" stroke="#0F172A" stroke-width="1.5" stroke-linejoin="round"/>`)
      .join("");
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}" fill="none"><g transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${s.toFixed(3)})">${body}</g></svg>`;
    fs.writeFileSync(`${OUT}/${variant}-${i}.png`, png(svg, SIZE));
    fs.writeFileSync(`${OUT}/${variant}-${i}@2x.png`, png(svg, SIZE * 2));
    const fallback = variant === "plane" ? "auto" : "pointer";
    const u1 = `url("/cursors/${variant}-${i}.png")`;
    const u2 = `url("/cursors/${variant}-${i}@2x.png")`;
    // Two declarations: browsers that don't take image-set() in cursor keep the first (plain PNG).
    cursorValue[variant] = `cursor: ${u1} ${hx} ${hy}, ${fallback};\n    cursor: -webkit-image-set(${u1} 1x, ${u2} 2x) ${hx} ${hy}, ${fallback};`;
  }
  const sel = i === REST ? `html, html[data-plane="${i}"]` : `html[data-plane="${i}"]`;
  const hov = i === REST ? `html :is(${INTERACTIVE}):not(:disabled), html[data-plane="${i}"] :is(${INTERACTIVE}):not(:disabled)` : `html[data-plane="${i}"] :is(${INTERACTIVE}):not(:disabled)`;
  rules.push(`  ${sel} {\n    ${cursorValue.plane}\n  }\n  ${hov} {\n    ${cursorValue.hover}\n  }`);
}

const css = `/* GENERATED by scripts/gen-cursors.mjs, do not edit. Paper-plane cursor (native, zero lag) that points
   where the mouse is heading: <PlaneDirection/> sets html[data-plane] to the heading bucket (0 = left,
   then clockwise every ${STEP}deg). Mouse/trackpad devices only; text fields keep the I-beam. */
@media (hover: hover) and (pointer: fine) {
${rules.join("\n")}
  html :is(input:not([type="checkbox"]):not([type="radio"]):not([type="submit"]):not([type="button"]):not([type="file"]), textarea, [contenteditable="true"]) {
    cursor: text;
  }
}
`;
fs.writeFileSync("src/app/plane-cursor.css", css);
console.log(`wrote ${fs.readdirSync(OUT).length} cursor PNGs and src/app/plane-cursor.css (rest bucket ${REST})`);
